[package]
name = "parsec"
version = "0.1.0"
authors = ["Paul Howard <paul.howard@arm.com>",
           "Ionut Mihalcea <ionut.mihalcea@arm.com>",
           "Hugues de Valon <hugues.devalon@arm.com>"]
edition = "2018"

[[bin]]
name = "parsec"
path = "src/bin/main.rs"

[dependencies]
parsec-interface = { git = "https://github.com/parallaxsecond/parsec-interface-rs", tag = "0.5.1" }
rand = "0.7.2"
base64 = "0.10.1"
uuid = "0.7.4"
threadpool = "1.7.1"
std-semaphore = "0.1.0"
signal-hook = "0.1.10"
sd-notify = { version = "0.1.1" }
toml = "0.4.2"
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.7.1"
log = { version = "0.4.8", features = ["serde"] }
pkcs11 = { version = "0.4.0", optional = true }
picky-asn1-der = { version = "0.2.2", optional = true }
picky-asn1 = { version = "0.2.1", optional = true }
tss-esapi = { version = "2.0.0", optional = true }
bincode = "1.1.4"
structopt = "0.3.5"
derivative = "1.0.3"
arbitrary = { version = "0.4.0", features = ["derive"], optional = true }

[dev-dependencies]
parsec-client-test = { git = "https://github.com/parallaxsecond/parsec-client-test", tag = "0.1.12" }
num_cpus = "1.10.1"

[build-dependencies]
bindgen = "0.50.0"
cargo_toml = "0.7.0"
toml = "0.4.2"
serde = { version = "1.0", features = ["derive"] }

[package.metadata.config]
mbed-crypto-version = "mbedcrypto-2.0.0"

[features]
default = ["mbed-crypto-provider", "pkcs11-provider"]
mbed-crypto-provider = []
pkcs11-provider = ["pkcs11", "picky-asn1-der", "picky-asn1"]
tpm-provider = ["tss-esapi", "picky-asn1-der", "picky-asn1"]
fuzz = ["parsec-interface/fuzz", "arbitrary"]
