[package]
name = "parsec-service"
version = "0.4.0"
authors = ["Anton Antonov <anton.antonov@arm.com>",
           "Paul Howard <paul.howard@arm.com>",
           "Ionut Mihalcea <ionut.mihalcea@arm.com>",
           "Hugues de Valon <hugues.devalon@arm.com>"]
description = "A language-agnostic API to secure services in a platform-agnostic way"
license = "Apache-2.0"
repository = "https://github.com/parallaxsecond/parsec"
readme = "README.md"
keywords = ["security", "service"]
categories = ["cryptography", "hardware-support"]
edition = "2018"

[[bin]]
name = "parsec"
path = "src/bin/main.rs"

[dependencies]
parsec-interface = "0.20.0"
rand = { version = "0.7.2", features = ["small_rng"] }
base64 = "0.10.1"
uuid = "0.7.4"
threadpool = "1.7.1"
std-semaphore = "0.1.0"
signal-hook = "0.1.10"
sd-notify = { version = "0.1.1" }
toml = "0.4.2"
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.7.1"
log = { version = "0.4.8", features = ["serde"] }
pkcs11 = { version = "0.4.0", optional = true }
picky-asn1-der = { version = "0.2.2", optional = true }
picky-asn1 = { version = "0.3.0", optional = true }
tss-esapi = { version = "4.0.9-alpha.1", optional = true }
bincode = "1.1.4"
structopt = "0.3.5"
derivative = "2.1.1"
version = "3.0.0"
hex = "0.4.2"
psa-crypto = { version = "0.5.0" , default-features = false, features = ["operations"], optional = true }
zeroize = { version = "1.1.0", features = ["zeroize_derive"] }
picky-asn1-x509 = { version = "0.3.2", optional = true }
users = "0.10.0"
libc = "0.2.72"

[dev-dependencies]
ring = "0.16.12"
lazy_static = "1.4.0"
rsa = "0.3.0"
rand = "0.7.3"
sha2 = "0.9.1"

[build-dependencies]
bindgen = "0.54.0"
cargo_toml = "0.7.0"
toml = "0.4.2"
serde = { version = "1.0", features = ["derive"] }

[package.metadata.docs.rs]
features = ["docs"]

[features]
default = []
no-parsec-user-and-clients-group = []
mbed-crypto-provider = ["psa-crypto"]
pkcs11-provider = ["pkcs11", "picky-asn1-der", "picky-asn1", "picky-asn1-x509", "psa-crypto"]
tpm-provider = ["tss-esapi", "picky-asn1-der", "picky-asn1", "picky-asn1-x509"]
all-providers = ["tpm-provider", "pkcs11-provider", "mbed-crypto-provider"]
docs = ["pkcs11-provider", "tpm-provider", "tss-esapi/docs", "mbed-crypto-provider"]
