[core_settings]
log_level = "error"

[listener]
listener_type = "DomainSocket"
timeout = 200 # in milliseconds

[[key_manager]]
name = "on-disk-manager"
manager_type = "OnDisk"

[[provider]]
provider_type = "MbedProvider"
key_id_manager = "on-disk-manager"

[[provider]]
provider_type = "TpmProvider"
key_id_manager = "on-disk-manager"
tcti = "mssim"

[[provider]]
provider_type = "Pkcs11Provider"
key_id_manager = "on-disk-manager"
library_path = "/usr/local/lib/softhsm/libsofthsm2.so"
user_pin = "123456"
# The slot_number mandatory field is going to be added by the find_slot_number.sh script
# to the last line of this file in the form:
# slot_number = 123456
