name: Continuous Integration

on: [push, pull_request]

jobs:
  all-providers:
    name: Various tests targeting a Parsec image with all providers included
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the container
        run: docker build -t all-providers e2e_tests/provider_cfg/all
      - name: Run the container to execute the test script
        run: docker run -v $(pwd):/tmp/parsec -w /tmp/parsec all-providers /tmp/parsec/ci.sh all

  mbed-crypto-provider:
    name: Integration tests using Mbed Crypto provider
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the container
        run: docker build -t mbed-crypto-provider e2e_tests/provider_cfg/mbed-crypto
      - name: Run the container to execute the test script
        run: docker run -v $(pwd):/tmp/parsec -w /tmp/parsec mbed-crypto-provider /tmp/parsec/ci.sh mbed-crypto

  pkcs11-provider:
    name: Integration tests using PKCS 11 provider
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the container
        run: docker build -t pkcs11-provider e2e_tests/provider_cfg/pkcs11
      - name: Run the container to execute the test script
        run: docker run -v $(pwd):/tmp/parsec -w /tmp/parsec pkcs11-provider /tmp/parsec/ci.sh pkcs11

  tpm-provider:
    name: Integration tests using TPM provider
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the container
        run: docker build -t tpm-provider e2e_tests/provider_cfg/tpm
      - name: Run the container to execute the test script
        run: docker run -v $(pwd):/tmp/parsec -w /tmp/parsec tpm-provider /tmp/parsec/ci.sh tpm

  installation-tests:
    name: Installation tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and run the container
        run: e2e_tests/installation_tests/run-installation-tests.sh
